############################################################
#
# See http://www.appveyor.com/docs/appveyor-yml for many more options
#
# Credit for a lot of this file goes to RamblingCookieMonster:
# http://ramblingcookiemonster.github.io/PSDeploy-Inception/
#
############################################################

# To encrypt a value in AppVeyor, go to the Account menu and choose "Encrypt data"
environment:
    NugetApiKey:
        secure: 5WCRuuF+sk5Mjnt5cL6uJw4cMU2QzDNE8uBXOw2hXSujE93zxRcROS3ZM1w85ui3

os: WMF 5

# Skip commits if they involve the readme
skip_commits:
    message: /updated readme.*|update readme.*s/

# Nothing to build - the magic all happens in the "test script."
# We use the test script instead of the build script because it can abort the build.
build: false

test_script:
    - ps: . .\Build\AppVeyor.ps1
